### PR TITLE
Make hyperopt, bbopt, and networkx all play nice

### PR DESCRIPTION
**Pull request by gcoon151**
Specified versions of hyperopt and networkx that don't make bbopt unhappy.

### CODE REVIEW

**Comment by gcoon151** [comment]
I guess alternately you could remove hyperopt since in the issue I suggested duping mine to, you said it's only used by one script. If they both do similar tasks hyperopt looks like the more mature but I don't know how many places you use bbopt and how hard switching would be.

**Comment by MatthewScholefield** [comment]
Thanks for this! For clarification, I think bbopt is to hyperopt like keras is to tensorflow; it's just a wrapper/abstraction. Anyways, this fixes the problem so I'll go ahead and merge it.

**Comment by gcoon151** [comment]
@MatthewScholefield FYI. I'll confirm this fixes it when I have some time and send you another PR but, I submitted an issue to bbopt and they fixed their pin on old hyperopt/networkx stuff. 

version = "1.1.7" bbopt removes this requirement of sticking hyperopt and networkx. 

https://github.com/evhub/bbopt/issues/9

**Comment by astrowave** [comment]
Has this been fixed?  I've cloned the dev branch and installed Tensorflow 1.13.1 as is specified but I'm getting errors

> ERROR: bbopt 1.1.8 has requirement hyperopt>=0.2.1; python_version >= "3", but you'll have hyperopt 0.1.2 which is incompatible.

So I've installed bbopt 1.1.7.  Which installs hyperopt-0.2.2 networkx-2.2 and results  in errors again

> ERROR: mycroft-precise 0.3.0 has requirement hyperopt==0.1.2, but you'll have hyperopt 0.2.2 which is incompatible.
> ERROR: mycroft-precise 0.3.0 has requirement networkx==1.11, but you'll have networkx 2.2 which is incompatible.
>

**Pull request merged**
