### PR TITLE
Feature/script overhaul

### PR DESCRIPTION
**Pull request by MatthewScholefield**
This restructures the script system in Mycroft Precise to allow programmatic access. The largest benefit of this is it provides a simple way to add test cases for scripts which is super useful for identifying larger bugs that pop up with new changes.

This introduces a number of tests that can be run with `pytest` as follows:
```bash
source .venv/bin/activate
pip install pytest
pytest
```

### CODE REVIEW

**Review by davidwagnerkc — APPROVED** [review]
Looks great. Makes scripts callable from Python :+1: and adds tests 🎉 

Looks like there were some bug fixes in the `pdf` function and `threshold_decoder` - these also look good, but you might call these unrelated changes out in the description next time. 

🚢 it.

**Comment by MatthewScholefield** [comment]
Awesome. Ah yes, I forgot to mention those. In creating the tests, they failed off the start because of some edge cases so those changes make the tests pass.

**Comment by el-tocino** [comment]
No model changes? .3 models will still work?

**Comment by MatthewScholefield** [comment]
Correct, from an outside user calling Precise via scripts, there should be no difference.

**Pull request merged**
