### PR TITLE
Activate notify

### PR DESCRIPTION
**Pull request by lzufalcon**
add a running directory independent noitfier

### CODE REVIEW

**Comment by MatthewScholefield** [comment]
@lzufalcon This looks good. I just rebased it off of dev. One other thing, I forgot before merging the previous PR that we have a CLA for new contributors:

---
To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code contribution.
This agreement makes it crystal clear that along with your code you are
offering a license to use it within the confines of this project. You retain
ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by lzufalcon** [comment]
@MatthewScholefield just signed the CLA, please continue your merging if it is okay.

**Comment by MatthewScholefield** [comment]
@lzufalcon Sorry it took a while, but you should have just received an email for the second part.

**Comment by lzufalcon** [comment]
@MatthewScholefield just signed the second part ;-)

**Pull request merged**
